---
name: SelectionVisualizeUtilsTest
main: kim\present\utils\selectionvisualize\test\Main
version: 0.1.0
api: [ 5.0.0 ]
author: PresentKim
description: selection-visualize-utils virion test plugin

commands:
  selectionvisualize:
    description: "Toggle selection-visualize-utils test mode"
    permission: selectionvisualize.command
    aliases: [svu]

permissions:
  selectionvisualize.command:
    default: op

